### ISSUE TITLE
Power Supply

### ISSUE THREAD

**Issue by dingogar** [Bostwickenator/VisiTel#2]
While not code related, I did want to reach out and ask if there were other methods of supplying power to the barrel jack connection?

I just found one of these at a Goodwill in Austin, and sadly it did not come with the orignal included adapter. I can't wait to see if it outputs an image, I did the jostle test and things seem solid with the wires. Thanks!
![IMG_3760](https://github.com/Bostwickenator/VisiTel/assets/163790643/d34600c0-bcce-41ae-b3c2-dac8c0152b7c)

**Comment by Bostwickenator** [comment]
Yes it runs on a 15v DC power supply it draws 1 amp. Anything which hits
those specs should do it. If get yours working an hook it up send me a WAV
file of your image and I'll display it on mine.

**Comment by dingogar** [comment]
Thanks so much! I'm going to order the proper adapters for power per spec, as well as source a good adapter for the audio as well. Your guide is very helpfuly, and I can not thank you enough for being around to help!

**Comment by dingogar** [comment]
Good Day!

I finally received the power adapter, however it seems like the unit may
not be in working order. While I may think im a hobbyist, I have nowhere
near the level of skill to look into the issue here, as much as I would
love to do so.
Attached are some internal shots of the Unit, everything seems like 1988,
smells like it too!

I have half a mind that maybe the adapter is bunk as well, perhaps!

Thanks!



*  Diego Garcia*
    Manager
Product Specialist

**Comment by Bostwickenator** [comment]
Sorry those images are not attached to the issue you'll need to upload them
on Github directly. It could be a few different things. Try flexing the
cables while near the Y joiner a little they were worn out on my unit. The
unit only powers up with the shutter is open and you should see a live
preview of the camera. It does take about a minute to warm up. Also be
careful opening it while plugged in. The CRT monitor needs very high
voltages to operate, you could get a significant shock. Best to leave it
a few minutes after turning it off before opening it up too.
Can you test the adapter with a multimeter?

**Comment by dingogar** [comment]
Removed previous Message for confusion - To any future VisiTel users - Please read over @Bostwickenator 's documentation, as they know all about these units! As they state, the power lines alongside the RJ11 lines are indeed extremely fragile- I tried a different adapter and jostled the lines, when hearing the classic CRT buzz you know its the wires!

I do not have a Power Supply or Multimeter handy as of posting this, however I want to make sure that there are no concerns over this adapter, as the cheapo one I pulled from Amazon did not seem to be sufficient. 

Next is to follow the guide and get some sound files!
![IMG_3795](https://github.com/Bostwickenator/VisiTel/assets/163790643/8211d899-31eb-40f5-a6f1-a39d4ae7ad94)
![IMG_3800](https://github.com/Bostwickenator/VisiTel/assets/163790643/f4398185-33f1-48f7-aa08-071c3dc127c4)
